
public class ExceptionDemo {

	public static void main(String[] args ) {
		// TODO Auto-generated method stub
		String name=null;// nullPoint exception
		System.out.println(name.length);
int num1=100;
int num2=num1/0;//arithmatic exception
//String name "subendu";
		int arr[]= {12,33,36};
	System.out.println(arr[4]);//array outbound exception
		
int i=Integer.parseInt(name);//numberpoint excetion
System.out.println("inside exception class");
System.out.println("the vale of division is:"+num2);
	}
}

